version: '3.8'

services:
 mongo:
  build: .
  image: mongocustom:latest
  container_name: mongodb
  hostname: mongodb
  networks:
   - mongonet
  ports:
   - 27017:27017
  restart: always
  environment:
   - MONGO_INITDB_ROOT_USERNAME=nbd
   - MONGO_INITDB_ROOT_PASSWORD=nbdpassword
  #command: --config /etc/mongod.conf
  healthcheck:
   test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
   interval: 10s
   timeout: 2s
   retries: 5

 mongoinit:
  build: .
  image: mongocustom:latest
  hostname: mongodbinit
  container_name: mongodbinit
  networks:
   - mongonet
  depends_on:
   - mongo
  command: >
   mongosh --host mongodb:27017 --username nbd --password nbdpassword --authenticationDatabase admin --eval
   '
   rs.initiate();
   '
networks:
 mongonet: {}